reset inventory
fu-js/j-surviv-SDK pull request #41
Opened 2024-09-12 10:19 UTC by DuongMinhSon16012004

2024-09-12 10:30 UTC, DAN3002 requested changes

2024-09-12 10:30 UTC, DAN3002 commented on src/main/java/jsclub/codefest2024/sdk/model/GameMap.java
> +            if (!currentPlayer.getIsAlive()) {
Chỗ này em viết 1 hàm trong inventory là `reset()` cho clear nhé.

2024-09-12 11:55 UTC, dangNguyenDinh commented on src/main/java/jsclub/codefest2024/sdk/model/GameMap.java
> +            if (!currentPlayer.getIsAlive()) {
chữa cả lỗi hiển thị nữa nhé các bạn, chết xong hồi sinh tôi vẫn mặc giáp

2024-09-13 15:02 UTC, DAN3002 approved these changes

2024-09-13 15:02 UTC, merged